apiVersion: v1
kind: Namespace
metadata:
  name: hey
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hey
  namespace: hey
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hey
    namespace: hey
---
apiVersion: v1
kind: Pod
metadata:
  name: hey
  namespace: hey
spec:
  serviceAccountName: hey
  containers:
    - name: hey
      image: dominikbraun/hey
      imagePullPolicy: Always
      stdin: true
      tty: true
      env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP