apiVersion: v1
kind: Pod
metadata:
  name: hey
  namespace: default
spec:
  containers:
    - name: hey
      image: dominikbraun/hey
      imagePullPolicy: Always
      stdin: true
      tty: true
      env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP